# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WidgetPOC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.3'
pod 'ObjectMapper', '~> 2.2'
pod 'RealmSwift', '~> 2.4.2'
pod 'ObjectMapper+Realm', '~> 0.2'
  # Pods for WidgetPOC

end

target 'WidgetPOCExtension' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 4.3'
   pod 'ObjectMapper', '~> 2.2'
   pod 'RealmSwift', '~> 2.4.2'
   pod 'ObjectMapper+Realm', '~> 0.2'
   
  # Pods for WidgetPOCExtension

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0.2'
        end
    end
end

